version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-{{ .Branch }}-
            - npm-master-
      - run: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:12
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run test

workflows:
  version: 2

  test:
    jobs:
      - install
      - test:
          requires:
            - install
